WIP: various enhancements
ImagingDataCommons/idc-index pull request #23
Opened 2024-01-02 19:28 UTC by fedorov

* use dedicated logger
* improve manifest download function to identify the right endpoint and support destination directory to address #17
* keep IDC version in a variable
* reorganize the query to be consistent with the comments and use bucket column

2024-01-02 19:31 UTC, fedorov commented
@vkt1414 can you help me debug this PR? I can't understand why, but `download_from_manifest` function does not seem to download anything, even though if I copy the s5cmd command it is using, everything works as expected!

2024-01-02 21:23 UTC, vkt1414 commented
> @vkt1414 can you help me debug this PR? I can't understand why, but `download_from_manifest` function does not seem to download anything, even though if I copy the s5cmd command it is using, everything works as expected!

The sample manifests for aws and gcp do not seem to be present. and `logger.info("Total size of files to download: ", float(total_size)/1000, "GB")` we may need to cast the floating number to string here.

2024-01-02 21:28 UTC, fedorov commented
I added the test manifests now.

2024-01-02 23:05 UTC, fedorov commented
I still need to fix few more functions, and unify download by means of the manifest for all download functions. These tests are known to fail...


```
======================================================================
FAIL: test_download_dicom_series (tests.idcindex.TestIDCClient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/af61/github/idc-index/tests/idcindex.py", line 53, in test_download_dicom_series
    self.assertNotEqual(len(os.listdir(temp_dir)),0)
AssertionError: 0 == 0

======================================================================
FAIL: test_download_from_selection (tests.idcindex.TestIDCClient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/af61/github/idc-index/tests/idcindex.py", line 59, in test_download_from_selection
    self.assertNotEqual(len(os.listdir(temp_dir)),0)
AssertionError: 0 == 0

```

2024-01-04 17:59 UTC, fedorov commented
I think finally understand the source of the problem. I was creating temp file using `with`, and was passing the name of that file to `s5cmd` inside `with`, which means `s5cmd` had to open that temporary file simultaneously, which I think might have triggered closing of the original handle and deletion of the file. I am using python 3.10, and (surprisingly to me), the API of `tempfile` evolved since 3.10 (see https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile). After moving `s5cmd` invocation outside of the `with` branch, it works!

2024-01-04 18:54 UTC, fedorov commented
@vkt1414 can you take another look? I suggest I merge this, manually create 0.2.8 release, upload the new index, and then trigger GA for updating the package. I am also going to manually re-tag "latest". For now, I think this is most expedient.

2024-01-04 18:57 UTC, vkt1414 commented
> @vkt1414 can you take another look? I suggest I merge this, manually create 0.2.8 release, upload the new index, and then trigger GA for updating the package. I am also going to manually re-tag "latest". For now, I think this is most expedient.

Sure. I'll run the tests command on windows and linux and let you know in a few minutes.

2024-01-04 19:16 UTC, vkt1414 requested changes

2024-01-04 19:16 UTC, vkt1414 commented on idc_index/index.py
> +        process = subprocess.run(cmd, capture_output=(not quiet), text=(not quiet)))
there seems to be an extra parantheses here at the end

2024-01-04 19:16 UTC, vkt1414 commented on idc_index/index.py
> +        if process.stderr.startswith('ERROR'):
![image](https://github.com/ImagingDataCommons/idc-index/assets/115020590/f77601d2-4e22-4c78-a238-c85ab21a71bf)


![image](https://github.com/ImagingDataCommons/idc-index/assets/115020590/93a37050-726e-4438-a836-c39066b39a09)

2024-01-04 19:17 UTC, vkt1414 commented on idc_index/index.py
> +        if process.stderr.startswith('ERROR'):
I'll try this on a jetstream vm too, just in case. And I realized I cannot run the tests on windows yet because of the prerequisites.

2024-01-04 19:48 UTC, vkt1414 commented on idc_index/index.py
> +        if process.stderr.startswith('ERROR'):
I could replicate the same errors on a jetstream vm too

2024-01-04 21:36 UTC, fedorov commented
Glad you caught that! I did what I thought was an inconsequential change, and didn't bother to rerun the tests. It should be fixed now. Fortunately, it will be easy to catch this with GA in the future.

2024-01-04 21:42 UTC, vkt1414 approved these changes
The tests ran fine on ubuntu as well now. 

Yes, I incorporated the tests step atleast in one of the gha in one of the PRs.

2024-01-04 21:47 UTC, merged